spring:
  application:
    name: Anime Service

  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never
  tomcat:
    threads:
      max: 20
